-- =====================================================================
-- Weekly market-intelligence briefings (linens, disposables, tariffs,
-- technology), generated by the market-insights edge function (Claude +
-- web search) and cached so all users read the latest. Idempotent.
-- Requires 0001_procurement_schema.sql (uses can_edit_procurement()).
-- =====================================================================
create table if not exists public.market_insights (
  id         text primary key,           -- "MI-<week_of>"
  week_of    date not null,
  as_of      timestamptz not null default now(),
  text       text not null default '',
  sources    jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists market_insights_week_idx on public.market_insights (week_of desc);

alter table public.market_insights enable row level security;

drop policy if exists "market auth read"     on public.market_insights;
create policy "market auth read"     on public.market_insights for select to authenticated using (true);
drop policy if exists "market editor write"  on public.market_insights;
create policy "market editor write"  on public.market_insights for all to authenticated using (can_edit_procurement()) with check (can_edit_procurement());
